version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_db
    expose:
      - 5432
    ports:
      - '5432:5432'